### ISSUE TITLE
Close Tab

### ISSUE THREAD

**Issue by creold** [linuz90/open-in-figma#1]
Hi, Fabrizio. Good extension for Chrome. But after opening URL link from Chrome in Figma, the browser still has an empty tab. Can you add the automatic closing of this empty tab in Chrome?

**Comment by linuz90** [comment]
Hi! Yes it's definitely something I'd like to add, and also click on the extension icon to disable it. I'll give it a shot in the weekend if I have time, I'm working on this in the spare time.

**Comment by creold** [comment]
Thanks. I understand, I also write JS scripts for Adobe Photoshop and Illustrator in my spare time.
