### ISSUE TITLE
It's not working on New Chrome

### ISSUE THREAD

**Issue by thexclu** [linuz90/open-in-figma#4]
I try to open the link in new Chrome version, it's close automatically but not show up on figma.

**Comment by linuz90** [comment]
Just tested it and it seems to work. The problem with version 0.3 for me is that it doesn't auto-close the tab anymore, and extension seems to work even when disabled. Are you experiencing this @creold?

**Comment by creold** [comment]
@designedbyclu which version of Chrome? Help> About Google Chrome. Do you have the Figma desktop app installed and does the extension just close the tab?

**Comment by creold** [comment]
@linuz90 chrome://extensions/ is there any error in version 0.3? I tested new version on the Mac OS High Sierra, Chrome v.69.0.3497.92 (64 bit) and Windows 7, Chrome v.68.0.3440.106 (32 bit). On / off, close the tab, redirect to the Figma app work well. Test video https://dl.dropboxusercontent.com/s/4chre48uxqvtw8v/openfigma_v_0_3.mp4

**Comment by thexclu** [comment]
This is my version of Chrome.
![image](https://user-images.githubusercontent.com/26009982/45584066-dab0ef00-b8ff-11e8-8d7d-ed3e6c3925e5.png)
And my version of "Open in Figma" is 0.2 
![image](https://user-images.githubusercontent.com/26009982/45584127-1ac4a180-b901-11e8-90ad-6fe52bd6fee9.png) 
Just downloaded again from the website.

![open_in_figma_0 2_failed](https://user-images.githubusercontent.com/26009982/45584264-0aadc180-b903-11e8-8605-40a049b59200.gif)

**Comment by thexclu** [comment]
I just updated my extension to V0.3.
![image](https://user-images.githubusercontent.com/26009982/45584359-b0156500-b904-11e8-93ce-774407962f4e.png)

Still the same, can't reach to my desktop app
![open_in_figma_0 3_failed](https://user-images.githubusercontent.com/26009982/45584347-878d6b00-b904-11e8-98de-a6072b02e359.gif)

**Comment by creold** [comment]
I see the problem, it is not in the version of Chrome. For new users we need to intercept this window in the extension, in which we give permission to open the link in the Figma desktop app.

![image](https://user-images.githubusercontent.com/32217031/45593325-9a07b300-b99d-11e8-9c7a-60b42fd16286.png)

**Comment by thexclu** [comment]
it's close too fast, i can't allow the permission.

**Comment by creold** [comment]
I know. The Extension sent the file to Figma app and closed the tab, but Chrome, due to the security setting, requested permission to open the Figma.  I am preparing an update with a solution to this problem.

**Comment by creold** [comment]
@designedbyclu , @linuz90 try the new version https://github.com/creold/open-in-figma . It's better to delete the old version before installing the extension version 1.0.

**Comment by linuz90** [comment]
Awesome, I'll check if it works on my Mac tonight or in the weekend (super busy at work rn). If we push it I'll add you as a co-author on the website and on the Chrome store page

**Comment by thexclu** [comment]
Working perfectly. Thanks for fix this up.

**Comment by creold** [comment]
@designedbyclu after the release of Google Web Store, you can already install the extension from there.

**Comment by linuz90** [comment]
Ok finally had the time to try this. Version 0.3 (already merged here) works perfectly in new Chrome, while version 1.0 doesn't automatically close the tab. Should I just push 0.3 on the Chrome Web Store?

Also not a fan of the setup instructions automatically opening in Chrome. I think the permissions popup just shows every time until you check the option, so it's not really worth showing an entire page with instructions for it. What do you think?

**Comment by creold** [comment]
In version 1.0, for tabs to close, you need to activate it once on the options page. I put this in the settings to avoid possible problems with the file type association popup.

If the extension immediately after the installation will automatically close the tabs, then new users will not be able to select an option from the popup “Always open these links associated with this app" option. This is what caused the problem for @designedbyclu.

I now understood, since I removed the automatic closing tab, then a new user can configure a popup for associating file types. And maybe the help page after installation is not needed. Check last commit for v.1.0 https://github.com/creold/open-in-figma.

I would write in Chrome Web Store that the extension v.1.0 has a settings page and that in the popup when the first start the user should activate the checkbox.

**Comment by creold** [comment]
@linuz90, hey. Do you plan to make an update 1.0 in the Chrome Web Store? https://github.com/creold/open-in-figma

**Comment by linuz90** [comment]
Hi there, yes for sure! I was super busy in the last few weeks but I’ll
make sure to find the time this weekend or the next one.
